name: sklearn-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip=23.0
  - pip:
    - azure-ai-ml>=1.12.0
    - azure-identity>=1.15.0
    - scikit-learn>=1.3.0
    - joblib>=1.3.0
    - pandas>=2.0.0
    - numpy>=1.24.0
    - pyyaml>=6.0.0